pkgname = "dbmodels"
output = "internal/repository/db/models"
add-enum-types = true
add-global-variants = true
no-tests = true
wipe = true

[mysql]
  dbname = "db_todo"
  host   = "localhost"
  port   = 3306
  user   = "root"
  pass   = "root"
  sslmode = "false"